version: "3.8"

services:
  postgres-event:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=event
      - POSTGRES_USER=aleksei
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"